services:
  postgres:
    image: postgres:16
    container_name: kasaflex_postgres
    restart: always
    environment:
      POSTGRES_DB: kasaflex_db
      POSTGRES_USER: kasaflex_user
      POSTGRES_PASSWORD: kasaflex_root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  influxdb:
    image: influxdb:2.7
    container_name: kasaflex_influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: Admin12345
      DOCKER_INFLUXDB_INIT_ORG: kasaflex_org
      DOCKER_INFLUXDB_INIT_BUCKET: kasaflex_mesures
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: KasaflexToken123456
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2

volumes:
  postgres_data:
  influxdb_data:
  influxdb_config: