spring.application.name=api

# PostgreSQL (docker-compose)
spring.datasource.url=jdbc:postgresql://localhost:5432/kasaflex_db
spring.datasource.username=kasaflex_user
spring.datasource.password=kasaflex_root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# InfluxDB (docker-compose)
management.influx.metrics.export.uri=http://localhost:8086
management.influx.metrics.export.org=kasaflex_org
management.influx.metrics.export.bucket=kasaflex_mesures
management.influx.metrics.export.token=KasaflexToken123456
